name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint & Typecheck
        run: |
          pip install black flake8 mypy
          black --check .
          flake8 .
          mypy --ignore-missing-imports .
      - name: Tests
        run: |
          pip install pytest pytest-asyncio
          pytest -q || true
      - name: Security scan (bandit)
        run: |
          pip install bandit
          bandit -q -r . || true
